### ISSUE TITLE
Hi, will the evaluation code (mentioned in Sec 4.1) be made open source?

### ISSUE THREAD

**Issue by ChnQ** [ys-zong/VLGuard#2]

**Comment by ys-zong** [comment]
Yes, I'm currently cleaning the code and will release them in the next a few weeks. Please stay tuned.

**Comment by virajprabhu** [comment]
Great work! Any updates on releasing the evaluation code so that we can report performance on VLGuard?

**Comment by ys-zong** [comment]
Hi, I've uploaded the evaluation code using LLaVA as an example. You can also easily integrate other models. Please let me know if you have any trouble running it.

**Comment by virajprabhu** [comment]
Great, thanks!
