### ISSUE TITLE
Available model weights for post-hoc fintuned LLaVA?

### ISSUE THREAD

**Issue by ybwang119** [ys-zong/VLGuard#3]
Hi, I find your work valuable and want to replicate the experimental results. The ideas as well as conclusions in this paper are interesting and inspiring. I just wonder is it convenient for you to make the weights of post-hoc fine-tuned LLaVA-1.5-7B-Lora weights available, or to provide the detailed 5k training data json file?

**Comment by ys-zong** [comment]
Hi, the post-hoc weights are released now.
