### ISSUE TITLE
Evaluation with released weight

### ISSUE THREAD

**Issue by SanghyeokSon** [ys-zong/VLGuard#5]
Thank you for sharing your excellent work.

I have a question regarding the trained model weights. 
I conducted an evaluation using the following command

`CUDA_VISIBLE_DEVICES=0 python VLGuard_eval.py --dataset unsafes --engine llava15-7b-mixed --metaDir /path/to/test.json --imageDir /path/to/VLGuard/test
`
However, I obtained a result of 0.23, which is different from the 0.90 mentioned in the paper. Did I miss any important steps?

**Comment by ys-zong** [comment]
Hi, since you passed `--dataset unsafes`, this script is calculating the attack success rate (the lower the better), and this number is percentage, i.e. 0.90%, or 0.23%. The difference is very minor and both of them are close to zero, and your result is actually better than what I reported in the paper. So I think it's totally fine.

**Comment by SanghyeokSon** [comment]
Thank you for the quick response!
I have one more question. How can I obtain the score for safe-safes?

I conducted an evaluation using the following command.
`CUDA_VISIBLE_DEVICES=0 python VLGuard_eval.py --dataset safe-safes --engine llava15-7b-mixed --metaDir /path/to/test.json --imageDir /path/to/VLGuard/test `

But, I cannot see the calculated score. When I checked the VLGuard_eval.py, it was set to calculate the score only when it was not a safe-safe case.
I understood the safe score as 1-ASR, so I checked this score, but it differed from what was described in the paper.

**Comment by ys-zong** [comment]
Below is from readme. Safe scores are for helpfulness (not 1-ASR), you can also check the paper for details.

----

To evaluate the helpfulness with safe_safes subset, run:
```
OPENAI_API_KEY="" # your OpenAI API key
python gpt4_evaluator.py --file_path results/safe_safes/{the_model_to_evaluate}.json --image_path /path/to/VLGuard/test --reference_path ./data/gpt4_safe_safes.json --output_path /path/to/save/results
```
It will calculate the win rate against GPT-4V.

**Comment by SanghyeokSon** [comment]
Thank you for the quick response! It'll be a great help!
