### ISSUE TITLE
Evaluate LLaVa Lora model on VLGuard

### ISSUE THREAD

**Issue by yiwei-chenn** [ys-zong/VLGuard#8]
Hello authors,

Thanks for your great work!

I am questioning that will you release the code to evaluate the llava-lora model in the future. I just find out that within the original llava-lora hf repo, there is no tokenizer file, so the load_model function in model_utils.py may not be useful.
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/90b5d672-4e58-46e3-b257-c12cb49d343c">

Thanks for your answering and waiting for your kindful reply~

**Comment by ys-zong** [comment]
Could you point me the model (hf link) that doesn't have a tokenizer file so I can check it? In case I forgot to upload the tokenizer, you can use the regular LLaVA tokenizer as they should be exactly the same. The Lora model loading should be very similar - you can refer to the [original LLaVA](https://github.com/haotian-liu/LLaVA/blob/c121f0432da27facab705978f83c4ada465e46fd/llava/eval/run_llava.py#L54) for this part.

**Comment by yiwei-chenn** [comment]
For example, I want to evaluate the LLaVA-v1.5-7B-lora model on VLGuard dataset, but the original [hf link](https://huggingface.co/liuhaotian/llava-v1.5-7b-lora) does not contain the tokenizer model. 

![image](https://github.com/user-attachments/assets/96545405-d739-45c9-9f9c-faf74fe4ea51)
the load_model function in model_utils.py does not specify the model_base and model_name in the function, so it could not load tokenizer correctly.

I changed your load_model function in model_utils.py into
```python
def load_model(model_path, model_base=None, model_name='llava', args=None):
    tokenizer, model, image_processor, context_len = load_llava_model(model_path=model_path, model_base=model_base, model_name=model_name, 
                                                                      attn_implementation='flash_attention_2', torch_dtype='float16', device_map='cuda',)
    processor = image_processor
    return model, tokenizer, processor
``` 

And I also modify line 66-68 of the main function in VLGuard_eval.py into 
```python
    for engine in args.engine:
        if engine == 'llava15-7b-lora':
            model_base = 'lmsys/vicuna-7b-v1.5'
        else:
            model_base = None
        model_name = engine
        model, tokenizer, processor = model_utils.load_model(model_mappings[engine], model_base, model_name, args)
        print("Loaded model: {}\n".format(engine))
``` 

Now, the evaluation code works successfully, I am not sure how do you eval this model originallly?

**Comment by ys-zong** [comment]
Your code is correct. It's just some minor differences in model loading, and the rest of the code should be the same.
